# Generated by Django 5.2.5 on 2025-08-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_timestamp_employee_userprofile_delete_user'),
        ('app', '0006_auto_20250823_1557'),
    ]

    operations = [
    ]
