# Generated by Django 5.2.5 on 2025-08-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20250823_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='WorkConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Expected work hours per day', max_digits=4)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in your currency', max_digits=10)),
                ('cutoff_type', models.CharField(choices=[('15_30', '15th and 30th of each month'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='15_30', max_length=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional bonus amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Configuration',
                'verbose_name_plural': 'Work Configurations',
            },
        ),
        migrations.CreateModel(
            name='DailyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('late_minutes', models.IntegerField(default=0)),
                ('late_deduction_minutes', models.IntegerField(default=0)),
                ('undertime_minutes', models.IntegerField(default=0)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Work Summary',
                'verbose_name_plural': 'Daily Work Summaries',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('15_30', '15th and 30th'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'start_date', 'end_date')},
            },
        ),
    ]
